# Nombre de la aplicación Spring Boot
spring.application.name=TennisErp

# Puerto en el que se ejecutará el servidor
server.port = 8086

# Configuración de la base de datos
# URL de conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tennisdb

# Nombre de usuario para conectarse a la base de datos
spring.datasource.username=root

# Contraseña para el usuario de la base de datos
spring.datasource.password=6865

# Clase del controlador JDBC para MySQL 8, necesaria para establecer la conexión con la base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto de Hibernate para MySQL, que especifica cómo Hibernate interactuará con la base de datos
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Ubicación de recursos estáticos (como imágenes, CSS, JS)
# Define que los recursos estáticos estarán en la carpeta `static` dentro del classpath
spring.web.resources.static-locations=classpath:/static/

spring.jpa.hibernate.ddl-auto=update

#Mostrar les sentencies sql que s'executen en la consola
#Propietat que permet imprimir en la consola la informacio formatejada.
#Si aquesta propietat esta activada, no s'imprimiran els parametres de les sentencies SQL.
spring.jpa.properties.hibernate.format_sql=true
#Propietat que permet que es mostri la consulta que s'estan executant
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.data.mongodb.core=DEBUG
#Propietat que permet que es mostrin els parametres que utilitzarem en les sentencies
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Mostrar todas las consultas SQL
spring.jpa.show-sql=true