spring.application.name=TennisErp
server.port = 8086
#url base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/tennisdb
#Nom usuari de la base de dades
spring.datasource.username=root
#Contrasenya de la base de dades
spring.datasource.password=abc.123
#Nom de la classe dels drivers de la base de dades per mysql8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Indiquem a JPA des de la plataforma que en conectarem a la base de dades
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
