spring.application.name=TennisErp
server.port=8086

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/tennisdb
spring.datasource.username=root
spring.datasource.password=user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rcosas66@gmail.com
spring.mail.password=lpcisunypikpvtgp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
